### ISSUE TITLE
Supported versions of Delphi

### ISSUE THREAD

**Issue by feammer** [Coldzer0/IDA-For-Delphi#9]
since there are many versions of delphi:1-7, 2005, 2006, 2007, 2009, 2010, XE-XE8、10、10.1、10.2、10.3
I want to know which version this plug-in supports.

**Comment by Coldzer0** [comment]
That's a good question!

I tested it with Delphi 10.2 to Delphi 11 

And right now, I've Delphi 12. I will check it.

If you have any other version that you can test that would be great.

**Comment by feammer** [comment]
I appreciate you replying so fast.
I'm testing it using Delphi 7 and  IDA 7.0.170914 Windows x64 (32-bit address size) but encounter a new problem:
---
C:\Users\windows10\Desktop\rename delphi functions.py: 'module' object has no attribute 'compiled_binpat_vec_t'
Traceback (most recent call last):
  File "C:\Program Files\IDA 7.0\python\ida_idaapi.py", line 553, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Users/windows10/Desktop/rename delphi functions.py", line 85, in <module>
    patterns = ida_bytes.compiled_binpat_vec_t()
AttributeError: 'module' object has no attribute 'compiled_binpat_vec_t'

**Comment by Coldzer0** [comment]
I don't think it will work with IDA older than 7.6.
You can check the older commits for a working version of IDA 7.0
